version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "export DJANGO_SETTINGS_MODULE=ImageCraftsman.settings &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              gunicorn ImageCraftsman.asgi:application -c gunicorn_config.py"
    volumes:
      - ./media/:/usr/src/ImageCraftsman/media/
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
      - memcached
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - 5432:5432

  memcached:
    # Определите сервис Memcached
    image: memcached:latest
    ports:
      - 11212:11211 # Откройте порт Memcached

volumes:
  postgres_data:
