# Generated by Django 4.2.5 on 2023-09-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ImageCraftApp", "0002_image_link_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsubscriptionplan",
            name="premium_thumbnail_size",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="customsubscriptionplan",
            name="thumbnail_size",
            field=models.PositiveIntegerField(),
        ),
    ]
