# Generated by Django 4.2.5 on 2023-09-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ImageCraftApp",
            "0003_alter_customsubscriptionplan_premium_thumbnail_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customsubscriptionplan",
            name="premium_thumbnail_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
