# Generated by Django 4.2.5 on 2023-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ImageCraftApp", "0004_alter_customsubscriptionplan_premium_thumbnail_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail_Basic",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="image",
            name="thumbnail_Premium",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
