# Generated by Django 4.2.5 on 2023-10-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ImageCraftApp", "0008_image_expiration_date_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="thumbnail_Basic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="image",
            name="thumbnail_Premium",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
